### ISSUE TITLE
Object type <class 'str'> cannot be passed to C code

### ISSUE THREAD

**Issue by wolfgangmay** [hecoter/hm3u8dl_cli#11]
你好，问一下 

使用的是 编译后的版本

**这个是加密的m3u8**
hm3u8dl_cli_v0.3.1.exe "https://v7.dious.cc/20220910/LgiDaGPc/1500kb/hls/index.m3u8" -title "dahui0910" -key "d8d277a6ddaac8a8"
报错是
Maybe the key is wrong.
Object type <class 'str'> cannot be passed to C code

**这个是没有加密的m3u8**
hm3u8dl_cli_v0.3.1.exe "https://cdn7.caoliqi.com:65/20220910/X6Krx7YD/1695kb/hls/index.m3u8" -title "dahui0910-1"
报错是
Maybe the key is wrong.
a bytes-like object is required, not 'str'

请查看一下

**Comment by hecoter** [comment]
感谢反馈，是base_uri解析问题，已解决，使用新版本即可，另外key可以自动解析，只输入m3u8url 可自动解析下载
