### ISSUE TITLE
__init__() missing 1 required positional argument: 'method' [Finished in 2.7s]

### ISSUE THREAD

**Issue by Jerry080801** [hecoter/hm3u8dl_cli#14]

**Comment by Jerry080801** [comment]
__init__() missing 1 required positional argument: 'method'
MacBook-Pro:Downloads jerry2$ hm3u8dl_cli "url" -title "a+b" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg=="
__init__() missing 1 required positional argument: 'method'
MacBook-Pro:Downloads jerry2$ hm3u8dl_cli "url" -title "a+b" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg=="

**Comment by hecoter** [comment]
你没有写m3u8url，这是个必填参数

**Comment by hecoter** [comment]
hm3u8dl_cli https//…… -title "a+b" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg=="
类似这样的，链接不能只用url代替

**Comment by Jerry080801** [comment]
> hm3u8dl_cli https//…… -title "a+b" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg==" 类似这样的，链接不能只用url代替

proxies must be a mapping 是?我没有加代理啊

**Comment by Jerry080801** [comment]
> hm3u8dl_cli https//…… -title "a+b" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg==" 类似这样的，链接不能只用url代替

他一直说缺少method,可是我用服务器版本,shell版本合python文件怎么加都说我没加method

**Comment by hecoter** [comment]
m3u8链接要用 “” 引号括起来，实在不行就留个联系方式吧

**Comment by Jerry080801** [comment]
> m3u8链接要用 “” 引号括起来，实在不行就留个联系方式吧

hm3u8dl_cli "https://video.acwing.com/9a000f5512704ff7a59e115f06d59033/cee61aa95ba0426f8f2c83f97b3f96bc-d05ad43cb593d6df0163d1193ee34737-od-S00000001-100000-encrypt-stream.m3u8?auth_key=1664388203-null-null-7d259dee4d5bceffa89edb7813d84203" -method "AES-128-ECB" -key "20Km1MtioSXwsxwUTFhxmg=="

__init__() missing 1 required positional argument: 'method'

**Comment by hecoter** [comment]
aliyun 自研ecb加密，算法涉及侵权，不提供解密
