### ISSUE TITLE
m3u8地址中带有？的地址无法正常解析下载

### ISSUE THREAD

**Issue by shutwin** [hecoter/hm3u8dl_cli#16]
m3u8地址中带有？的地址无法正常解析下载，该如何解决呢？只要地址中带有问号的，就会显示403错误，无法正常下载

**Comment by shutwin** [comment]
小鹅通地址，需要带有sign 参数，在python代码中调用的，无法下载成功。我看你源码中将地址中的？后面的参数都分割了，也就无法正常下载。

**Comment by hecoter** [comment]
官方更新，方法失效，在新版本中取消了对xet的解密 使用 `pip install --upgrade hm3u8dl_cli`进行更新
方法如下：
`from hm3u8dl_cli import m3u8download
m3u8url = 'https://encrypt-k-vod.xet.tech/9764a7a5vodtransgzp1252524126/11406af5387702306442914866/drm/v.f421220.m3u8?start=1301616&end=1422511&type=mpegts&sign=2e9a092b9f04fc44f66c725a4ea5b4dd&t=636eb831&us=INuqBqKUvV'
title = 'title'
m3u8download(m3u8url,title)`

![截图.png](https://img1.imgtp.com/2022/11/11/ySHo7Rh3.png)
