### ISSUE TITLE
hm3u8dl_gui 支持伪图片格式的m3u8下载吗？

### ISSUE THREAD

**Issue by Narut0123** [hecoter/hm3u8dl_cli#25]
最近常遇到伪装成图片格式的m3u8，内容格式如下
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXTINF:9,
https://qy.xmflv.cc/a25cBFMGUlEOAFQBAQlTVA0EX1UHUQdTBVJQAQgQWQkCDlIFUgNRWgAEUwQDCEIBBVEBBFEAQlY.png
#EXTINF:7,
https://qy.xmflv.cc/a9a2BAMABgUBAAFWBQZcAVMAAgQCUgIBCFcJAlYTC1oDXQQFAgUFDg8EBlMHAR5TBVFdAA5TEAA.png
#EXTINF:9,
https://qy.xmflv.cc/a432Bg8FVlQNBAcHA1AGBAQKDAdSCAMBBAoAW1FEWw1RDlIHDgBVXwMAAAIBBBVUUQsJVwgNFAE.png
#EXTINF:6,
https://qy.xmflv.cc/8ebaBFMFBgZYAgxRAwgAAVZYB1tRXFZaAg0LDFMXW18CCQQFUgAFDVYGC1QBABMEUVgHCwdQRAs.png
……（后面还有很多条，这里就不贴出来了）

hm3u8dl_cli文件夹里的decryptors目录下的FakeImage.py可以解密伪图片，请问hm3u8dl_gui 0.4.6可以使用该功能吗？

**Comment by hecoter** [comment]
可以下载，但是你的m3u8链接失效，可以将m3u8文件下载之后使用命令行下载

目前界面在测试中，不建议使用

命令行使用方法：

1. 安装python

2. 输入命令安装 `pip install --upgrade hm3u8dl_cli`

3. 下载： `hm3u8dl_cli "/home/hecoter/Downloads/b8060a2d6b620f45b3cfd4d58921fe2a.m3u8"`

   [![VzQoq.png](https://i.328888.xyz/2022/12/06/VzQoq.png)](http://imgloc.com/i/VzQoq)

   

![V6yxL.png](https://i.328888.xyz/2022/12/06/V6yxL.png)

**Comment by Narut0123** [comment]
> 可以下载，但是你的m3u8链接失效，可以将m3u8文件下载之后使用命令行下载
> 
> 目前界面在测试中，不建议使用
> 
> 命令行使用方法：
> 
> 1. 安装python
> 2. 输入命令安装 `pip install --upgrade hm3u8dl_cli`
> 3. 下载： `hm3u8dl_cli "/home/hecoter/Downloads/b8060a2d6b620f45b3cfd4d58921fe2a.m3u8"`
>    [![VzQoq.png](https://camo.githubusercontent.com/ecc7e5a45ec267b47dd10e48027f0818079c6adf35094995b69693ca2b57a667/68747470733a2f2f692e3332383838382e78797a2f323032322f31322f30362f567a516f712e706e67)](http://imgloc.com/i/VzQoq)
> 
> ![V6yxL.png](https://camo.githubusercontent.com/b531a08570dca1f6b928e22f86e2a711d7be6fcd57745abbf32e355d21425e66/68747470733a2f2f692e3332383838382e78797a2f323032322f31322f30362f563679784c2e706e67)

说来惭愧，不会用Python啊
就是因为不会使用Python才用hm3u8dl_gui的

**Comment by Narut0123** [comment]
> 

大佬，昨晚在吾爱论坛回复我的“hecoter12138”也是您吧

**Comment by Narut0123** [comment]
> 可以下载，但是你的m3u8链接失效，可以将m3u8文件下载之后使用命令行下载
> 
> 目前界面在测试中，不建议使用
> 
> 命令行使用方法：
> 
> 1. 安装python
> 2. 输入命令安装 `pip install --upgrade hm3u8dl_cli`
> 3. 下载： `hm3u8dl_cli "/home/hecoter/Downloads/b8060a2d6b620f45b3cfd4d58921fe2a.m3u8"`
>    [![VzQoq.png](https://camo.githubusercontent.com/ecc7e5a45ec267b47dd10e48027f0818079c6adf35094995b69693ca2b57a667/68747470733a2f2f692e3332383838382e78797a2f323032322f31322f30362f567a516f712e706e67)](http://imgloc.com/i/VzQoq)
> 
> ![V6yxL.png](https://camo.githubusercontent.com/b531a08570dca1f6b928e22f86e2a711d7be6fcd57745abbf32e355d21425e66/68747470733a2f2f692e3332383838382e78797a2f323032322f31322f30362f563679784c2e706e67)

大佬，昨晚在吾爱论坛回复我的“hecoter12138”也是您吧

**Comment by wansqh** [comment]
copyrightDRM怎么获取
