### ISSUE TITLE
KeyError: 'server'

### ISSUE THREAD

**Issue by sweetnotice** [hecoter/hm3u8dl_cli#26]
![image](https://user-images.githubusercontent.com/106159757/210127885-93bbfacc-917e-4abf-ab92-ed8985cd47a4.png)

**Comment by hecoter** [comment]
传入方式有错误吧，你是如何使用的？

**Comment by hecoter** [comment]
传入方式有错误吧，你是如何使用的？

**Comment by sweetnotice** [comment]
![image](https://user-images.githubusercontent.com/106159757/210128967-32ffdadf-fff3-4797-b3ad-8412951e9ddb.png)

**Comment by hecoter** [comment]
`from hm3u8dl_cli.util import M3U8InfoObj
from hm3u8dl_cli import m3u8download

m3u8InfoObj = M3U8InfoObj() # 示例化一个m3u8Info对象

m3u8InfoObj.m3u8url = 'https://hls.videocc.net/4adf37ccc0/a/4adf37ccc0342e919fef2de4d02b473a_3.m3u8'
m3u8InfoObj.title = '标题'

m3u8download(m3u8InfoObj) # 只需填一个参数`

改成类似这样使用吧，传入字典时参数必须完整，传入一个对象不需要

**Comment by sweetnotice** [comment]
感谢，可以了。最近是改了什么东西吗，我以前一直都是用这种方式传参的。

**Comment by hecoter** [comment]
之前感觉不够写法不够简洁，还需要自己记住各参数名称，为方便使用更改了传参模式，同时保留了之前字典传参的方式，可能有些小问题存在，因此建议使用传入对象的方式进行传参。
最近更新集中在util 类里面，新增了一些算法解密，只是还不实用，估计只有极少数喜欢纯算法的人才会使用，其他人貌似用不到
