### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xxoomlgb** [hecoter/hm3u8dl_cli#8]
大佬 这个软件咋用啊 能发我一个你的联系方式吗 能给个视频教程之类的吗

**Comment by hecoter** [comment]
看文档吧，不知道你具体在问什么

**Comment by xxoomlgb** [comment]
我用小白篇那个地址下载的软件 用tool里面那个yuku文件名的程序下载m3u8 显示不支持SAMPLE-AES-CTR解密 我是小白啊 搞不懂啊

**Comment by hecoter** [comment]
不支持youku
