### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -i "/Users/xk/Downloads/ffmpeg/123__.mp4" -c copy "/Users/xk/Downloads/ffmpeg/123___ffmpeg.mp4"'

### ISSUE THREAD

**Issue by hoooou** [hecoter/hm3u8dl_cli#9]
mac,python 3.10,已安装FFmpeg，命令行下成功执行，python调用报错
        cmd = f'{self.toolsPath["ffmpeg"]} -i "{self.temp_dir + ".mp4"}" -c copy "{self.temp_dir + "_ffmpeg.mp4"}" -loglevel panic'
        subprocess.call(cmd)
改为
        cmd = f'{self.toolsPath["ffmpeg"]} -i "{self.temp_dir + ".mp4"}" -c copy "{self.temp_dir + "_ffmpeg.mp4"}" -loglevel panic'
        subprocess.call(cmd,shell=True)
执行成功

**Comment by hecoter** [comment]
好的了解了，可以先将merge_mode设为1，不使用ffmpeg合并。
此问题会在下个版本修复。

**Comment by hoooou** [comment]
@hecoter 漏掉一个，merge.py 65行

**Comment by hecoter** [comment]
mac貌似没有单独的ffmpeg文件，所以想用ffmpeg需要自己安装到环境变量，与shell无关。
建议使用时merge_mode设为1，直接合并ts文件。
